version: '3.1'
services:
  app:
    build: .
    container_name: 'n7-api'
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - '3001:3001'
  database:
    image: 'mysql:8'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: 'n7-api-db'
    environment:
      MYSQL_ROOT_PASSWORD: pswd
    volumes:
      - ./mysql-volume:/var/lib/mysql
    ports:
      - '3308:3306'
