version: '3'
services:
  app:
    build: .
    container_name: 'n7-api'
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - '3001:3001'
